In [1]:
#1.
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a.reshape(2, -1)
print(b)

[[1 2 3]
 [4 5 6]]


In [2]:
#2.
z = np.zeros(5)
o = np.ones(5)
print(z, o)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [3]:
#3.
a = np.linspace(5, 50, 10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [4]:
#4.
l = [1,2,3,4]
a = np.array(l)
print(a)

[1 2 3 4]


In [5]:
#5.
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#6.
a = np.arange(16).reshape(4,4)
print(a[0])
print(a[:, -1])

[0 1 2 3]
[ 3  7 11 15]


In [7]:
#7.
a = np.arange(16).reshape(4,4)
print(a[1::2, ::2])

[[ 4  6]
 [12 14]]


In [8]:
#8.
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
print(np.intersect1d(a,b))

[3 4]


In [9]:
#9.
a = np.array([1,6,8,10,12])
print(a[(a>=5)&(a<=10)])

[ 6  8 10]


In [10]:
#10.
a = np.random.randint(1,50,(3,2))
print(a.max(), a.min())

44 7


In [11]:
#11.
a = np.arange(9).reshape(3,3)
a = np.delete(a,1,axis=1)
a = np.insert(a,1,[10,10,10],axis=1)
print(a)

[[ 0 10  2]
 [ 3 10  5]
 [ 6 10  8]]


In [12]:
#12.
a = np.arange(6).reshape(3,2)
a[:,[0,1]] = a[:,[1,0]]
print(a)

[[1 0]
 [3 2]
 [5 4]]


In [13]:
#13.
a = np.random.randint(1,20,(3,3))
print(np.sort(a,axis=1))

[[ 5  9 14]
 [ 6 12 13]
 [ 3 12 13]]


In [14]:
#14.
a = np.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#15.
a = np.array([[3,2],[1,5],[4,1]])
print(a[a[:,1].argsort()])

[[4 1]
 [3 2]
 [1 5]]


In [16]:
#16.
a = np.array([1,2,2,3,3,3])
u, c = np.unique(a, return_counts=True)
print(dict(zip(u,c)))

{np.int64(1): np.int64(1), np.int64(2): np.int64(2), np.int64(3): np.int64(3)}


In [17]:
#17.
a = np.array([[1,2],[3,4]])
print(a.T)

[[1 3]
 [2 4]]


In [18]:
#18.
a = np.array([[2,1],[1,2]])
w,v = np.linalg.eig(a)
print(w, v)

[3. 1.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [19]:
#19.
A = np.array([[1,2],[3,4]])
B = np.array([8,18])
x = np.linalg.solve(A,B)
print(x)

[2. 3.]


In [20]:
#20.
a = np.array([1,2,3,4,5])
print(np.mean(a), np.median(a), np.std(a))

3.0 3.0 1.4142135623730951


In [21]:
#21.
import numpy as np

marks = np.array([list(map(int,input().split())) for _ in range(6)])

total = marks.sum(axis=1)
avg = total/4

print(total, avg)
print(marks[avg>70])

print(np.argsort(total)[-2])

print(marks.max(axis=0))

98 76 87 77 98 87
98 78 65 88 74  98
87 78 66 98 88 78
99 87 99 67 55 87 
67 89 76 88 99 76
78 89 99 86 57 77
[523 501 495 494 495 486] [130.75 125.25 123.75 123.5  123.75 121.5 ]
[[98 76 87 77 98 87]
 [98 78 65 88 74 98]
 [87 78 66 98 88 78]
 [99 87 99 67 55 87]
 [67 89 76 88 99 76]
 [78 89 99 86 57 77]]
1
[99 89 99 98 99 98]


In [22]:
#22.
import numpy as np

A = np.array([list(map(int,input().split())) for _ in range(2)])
B = np.array([list(map(int,input().split())) for _ in range(2)])

print(A+B)
print(A-B)
print(A@B)

print(A.T, B.T)

print(np.linalg.det(A))
if np.linalg.det(A)!=0:
    print(np.linalg.inv(A))

5 6
9 7
4 6
7 6
[[ 9 12]
 [16 13]]
[[1 0]
 [2 1]]
[[62 66]
 [85 96]]
[[5 9]
 [6 7]] [[4 7]
 [6 6]]
-18.999999999999996
[[-0.36842105  0.31578947]
 [ 0.47368421 -0.26315789]]


In [24]:
#23.
import numpy as np

a = np.array(list(map(int,input().split())))
b = a.reshape(2,-1)

print(b)
print(b.flatten())
print(np.sort(a))
print(np.sort(a)[::-1])
print(a.max(), a.min(), a.argmax(), a.argmin())

8 9 5 7 4 8 5 7
[[8 9 5 7]
 [4 8 5 7]]
[8 9 5 7 4 8 5 7]
[4 5 5 7 7 8 8 9]
[9 8 8 7 7 5 5 4]
9 4 1 4


In [27]:
#24.
import numpy as np

A = np.array([list(map(int,input().split())) for _ in range(2)])
B = np.array(list(map(int,input().split())))

if np.linalg.det(A)==0:
    print("Singular matrix")
else:
    X = np.linalg.solve(A,B)
    print(X)
    print(np.allclose(A@X,B))

2 4
8 6
9 5
[-1.7  3.1]
True


In [28]:
#25.
import numpy as np

a = np.arange(25).reshape(5,5)

print(a[0])
print(a[:,-1])
print(np.diag(a))
print(a[1:4,1:4])

a[a%2==0]=0
print(a)
print(np.sum(a%2!=0))

[0 1 2 3 4]
[ 4  9 14 19 24]
[ 0  6 12 18 24]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]
12


In [29]:
#26.
import numpy as np

a = np.array(list(map(int,input().split())))
val = int(input())

filtered = a[a>val]
a[a<0]=0

print(filtered)
print(len(filtered))
print(a)

5 -3 12 7 -1 9
6
[12  7  9]
3
[ 5  0 12  7  0  9]


In [30]:
#27.
import numpy as np

sales = np.array(list(map(int,input().split()))).reshape(12,1)

total = sales.sum()
avg = sales.mean()

print(total)
print(np.argmax(sales)+1)
print(np.argmin(sales)+1)
print(avg)
print(np.where(sales<avg)[0]+1)

100 200 150 300 250 400 350 450 500 600 550 700
4550
12
1
379.1666666666667
[1 2 3 4 5 7]


In [31]:
# Extended numpy questions
#1.
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
#2.
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
#3.
a = np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


In [34]:
#4.
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
#5.
a = np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


In [36]:
#6.
a = np.random.random((3,3,3))
print(a)

[[[0.63795633 0.77911453 0.64407707]
  [0.99010533 0.47135453 0.98681509]
  [0.75084184 0.69860294 0.99610233]]

 [[0.1984582  0.5205147  0.76154216]
  [0.62864937 0.47740693 0.53217457]
  [0.66963141 0.25996598 0.87762352]]

 [[0.62124592 0.82421804 0.74171131]
  [0.10257561 0.52081848 0.73183952]
  [0.36064712 0.2397141  0.64907196]]]


In [37]:
#7.
a = np.random.random((10,10))
print(a.min(), a.max())

0.012212600111831007 0.9949964889228944


In [38]:
#8.
a = np.random.random(30)
print(a.mean())

0.4599182709205331


In [39]:
#9.
a = np.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
#10.
a = np.random.random((5,5))
norm = (a - a.mean())/a.std()
print(norm)

[[-0.33396992 -0.50336123 -1.62615189  0.70304172 -0.87537947]
 [ 0.649773    1.1743186  -0.26732067 -1.87115925 -0.34700764]
 [-0.91627311 -0.88638583 -0.61274121  0.85333218  1.64089756]
 [ 0.98290507 -0.05741431 -0.44238298 -1.15326601  1.15184015]
 [ 0.71601063 -0.65163641 -0.44416395  1.58742213  1.52907284]]


In [41]:
#11.
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A @ B)

[[0.59686252 0.3657411 ]
 [0.97841522 0.5909427 ]
 [0.61772563 0.95712811]
 [0.76476359 0.74656684]
 [1.01855027 0.85046912]]


In [42]:
#12.
a = np.array([1,4,6,9,2,7])
a[(a>3)&(a<8)] *= -1
print(a)

[ 1 -4 -6  9  2 -7]


In [43]:
#13.
a = np.array([[2,1],[1,2]])
w, v = np.linalg.eig(a)
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [3. 1.]
Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [44]:
#14.
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
